site_url: https://docs.amis.work/
site_name: FastAPI-Amis-Admin
site_description: fastapi-amis-admin是一个拥有高性能,高效率,易拓展的fastapi管理后台框架.启发自Django-Admin,并且拥有不逊色于Django-Admin的强大功能.
repo_url: https://github.com/amisadmin/fastapi_amis_admin
edit_uri: edit/master/docs/zh/docs/
theme:
  name: material
  palette:
    scheme: default
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - content.code.annotate
markdown_extensions:
  - toc:
      permalink: true
  - markdown.extensions.codehilite:
      guess_lang: false
  - admonition
  - codehilite
  - extra
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tasklist
  - pymdownx.tilde

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid@9.4.3/dist/mermaid.min.js
  - https://hm.baidu.com/hm.js?0b1b8a60b3a22ae45d1f04245f409fe2
  - js/chat.js
  - js/sidecar-1.5.0.js

extra:
  alternate:
    - name: English
      link: /
      lang: en
    - name: 简体中文
      link: /zh/
      lang: zh

nav:
  - Tutorials:
      - index.md
      - tutorials/quickstart.md
      - 基础教程:
          - tutorials/basic/PageAdmin.md
          - tutorials/basic/FormAdmin.md
          - tutorials/basic/TemplateAdmin.md
          - tutorials/basic/ModelAdmin.md
          - tutorials/basic/ModelAction.md
          - tutorials/basic/Settings.md
          - tutorials/basic/Inheritance.md
          - tutorials/basic/i18n.md
          - tutorials/basic/_more.md
      - 高级教程:
          - tutorials/advanced/cli.md
          - tutorials/advanced/permission.md
          - tutorials/advanced/user-auth.md
          - tutorials/advanced/scheduler.md
          - tutorials/advanced/AdminApp.md
          - tutorials/advanced/structure.md
          - tutorials/advanced/debug.md
          - tutorials/advanced/_more.md
      - 拓展教程:
          - extended/about.md
          - extended/SQLModel.md
          - extended/alembic.md
      - about.md

  - API Reference:
      - Amis:
          - amis/types.md
      - Crud:
          - crud/RouterMixin.md
          - crud/BaseCrud.md
          - crud/SQLModelCrud.md
      - Admin:
          - amis_admin/BaseAdmin.md
          - amis_admin/RouterAdmin.md
          - amis_admin/PageSchemaAdmin.md
          - amis_admin/PageAdmin.md
          - amis_admin/TemplateAdmin.md
          - amis_admin/FormAdmin.md
          - amis_admin/ModelAdmin.md
          - amis_admin/ModelAction.md
          - amis_admin/AdminGroup.md
          - amis_admin/AdminApp.md
          - amis_admin/AdminSite.md
          - amis_admin/Settings.md
      - Utils:
          - utils/database.md
